import os

ftgDir = os.path.dirname(os.path.realpath(__file__))

# Directory where FortranCallGraph is located
# REQUIRED
FCG_DIR = ftgDir + '/../fortrancallgraph'

# Configuration file to be used by FortranCallGraph
# OPTIONAL: When omitted or None, config variables required by FortranCallGraph must be assigned here
# When empty string (''), FortranCallGraph's default (config_fortrancallgraph.py) will be used.
# Variables can always be overwritten here
FCG_CONFIG_FILE = 'config_fortrancallgraph.py'

# Location of the templates to be used 
# REQUIRED
TEMPLATE_DIR = ftgDir + '/templates/standalone'

# Directory where the test drivers generated by -r will be placed
# REQUIRED
TEST_SOURCE_DIR = ''

# List containing locations of the source files that will be modified by -c
# OPTIONAL: When omitted or None same as SOURCE_DIRS from FortranCallGraph's configuration
# Can be used for example, when preprocessed source files shall be analysed but original source files modified.
# Handle with care! -c creates backups (see BACKUP_SUFFIX) of the unmodified source files for later analyses, 
# but those are only used when SOURCE_DIRS and MODIFIY_SOURCE_DIRS are the same.
MODIFY_SOURCE_DIRS = None

# Suffix for backuped source files
# Will used by later analyses, for example when you first run -c and later -r
# OPTIONAL, default: 'ftg-backup'
BACKUP_SUFFIX = 'ftg-backup'

# Prefix of subroutines generated by -c, will be excluded from later analyses 
# Must fit to subroutine names defined in the template
# OPTIONAL, default: 'ftg_'
FTG_PREFIX = 'ftg_'

# Value of the template variable ${dataDir}
# OPTIONAL, default: '.'
TEST_DATA_BASE_DIR = '.'
